import React from 'react'
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: {
        absolute: 'bbb',
    },
    description: "Generated by create next app",
};

function About() {
    return (
        <div>About</div>
    );
}

export default About;